name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust and wasm-pack
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install wasm-pack
      run: |
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Build with wasm-pack
      run: wasm-pack build --release --target web

    # Upload the pkg directory as an artifact
    - name: Upload GitHub Pages artifact
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: ./

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
